---
language: "python"
python:
  - "3.7"

# Install python packages
install:
  - "pip install -r requirements.txt"

# Perform pre-checks
before_script:
  - "make lint"

# Perform testing of all scripts
script:
  - "make run"
...
